[workspace]
resolver = "2"

members = [
    "fbs-library",
    "fbs-runtime",
    "fbs-reactor",
    "fbs-resolver",
    "fbs-http-client",
    "fbs-amqp",
    "fbs-application",
    "liburing-sys",
    "libcurl-sys",
    "test-sandbox",
    "app-healthcheck",
]
